#!/bin/bash
# This script will switch between a Simple and Nested layout
# Author: Mik McLean
# Made for Hyperpie
# https://www.hyperpie.org

echo_c()
{
  w=$(stty size | cut -d" " -f2)       # width of the terminal
  l=${#1}                              # length of the string
  printf "%"$((l+(w-l)/2))"s\n" "$1"   # print string padded to proper width (%Ws)
}

clear

echo_c "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo_c "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo_c "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo_c "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo_c "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNXK000000KXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNNNNNNNNNNNNNWWMMMMMM"
echo_c "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXK0kxdolllllodxO0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNkllllllllllllllod0NWMMM"
echo_c "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0Okxdoc;,,,,,;:clox0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOxxkkkkkkkkxxl;,;o0NWMM"
echo_c "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKOkxdolclo:,,,,,,,,;ldkKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0kkxxxxxxxxxo:,;d0XWMM"
echo_c "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0Oxddl;,,cdl;,,,,,,,,;cdOKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNkc;;coooooooooodx0KNMMM"
echo_c "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKOxldo;,;:od:,,,,,,,,,,;lx0KNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXd;,;oOOOOOOOOOOOO0XNMMM"
echo_c "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0ko:loccodo:,,,,,,,,,,,,:dOKXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXxc:::ccccccccccccd0XWMM"
echo_c "MMMMMWXOkkkkkk0XNWMMMMMMMMMMMWKOkkkkkk0XNWN0kkkkkkOXNWMMMMMMMMMMMWXOkkkkkk0XNWN0kkkkkkkkkkkkkkkkkkkkkkkkkkO0XWMMMMMMMNX0OkkkkkkkkkkkkkkkkkkkkkkkkkkKXNMWXOkkkkkkkkkkkkkkkkkkkkkkkkkkOKNWMMMMN0kkkkkkkkkkkkkkkkkkkkkkkkkxxxoolllc:;,,,,,,,,,,,,,:dO0XNX0kkkkkkkkxxxxxxxxxxxxxxxxkkxOKXK0000000000000000KKNMMM"
echo_c "MMMMMW0c,,,;;;o0XWMMMMMMMMMMMNkc,,,,,;o0XWKl;,,;,,cOXWMMMMMMMMMMMWOc,,;,,,lOXWXd;;,;;,,;,,;,,;;;,,,,,,,,,,;;cxKNWMMWKdc;;;,,;,,,,,,,,,,,,,,,,,,;;,;xKNMW0l;,,,,,;;,,,,;,,;,,;,,,,;;,;:lOXWMMXo;,,;;,,,,,,,,;;,;,,;;,;;,;;;cdxl;,,,,,,,,,,,,,,,;cx000kl:;,,,,,,,,,,,,,,,,,,,,,,,,,,cOXNWWWWWWWWWWWWWWWWWWMMMM"
echo_c "MMMMMW0c,,,,,,l0XWMMMMMMMMMMMWO:,,,,,;o0XWKl,,,,,,cOXWMMMMMMMMMMMWOc,,,,,,lOXWXd;,,,,,,;;;;;;;;;;;;;;;;,,,,,,;o0NWW0l;,,,,,,;;;;;;;;;;;;;;;;;;;;;;:xKNMW0l,,,,,,,;;;;;;;;;;;;;;;;,,,,,,:xKNMXd;,,,,,,;;;;;;;;;;;;;;;;,,,,,,;okl,,,,,,,,,,,,,,,:d0KOd:,,,,,,;:;::;::::::::::::::::;lOXWMMMMMMMMMMMMMMMMMMMMMM"
echo_c "MMMMMW0c,,,,,,l0XWMMMMMMMMMMMWO:,,,,,;o0XWKl,,,,,,cOXWMMMMMMMMMMMWOc,,,,,,lOXWXd;,,,,,;dOOOOOOOOOOOOOOkc;,,,,,ckXNWk:,,,,,,lkOOOOOOOOOOOOOOOOOOOOOO0KNMW0l,,,,,,cxOOOOOOOOOOOOOOd:,,,,,,o0XWXo;,,,,,:dOOOOOOOOOOOOOOxc,,,,,,ckd;,,,,,,,,,,,,;cx0KKOo;,,,,,:x0OO00000000000000000OO0KXWMMMMMMMMMMMMMMMMMMMMMM"
echo_c "MMMMMW0c,,,,,,ckKXXXXXXXXXXXXKx:,,,,,;o0XWKl,,,,,,:xO0KKKKKKKKKKK0x:,,,,,,l0XWXd;,,,,,;d0KKKKKKKKKKKKK0l;,,,,,ckKNWk:,,,,,,lxOOOOOOOOOOOOOOOOOOOO0KXWWMW0l,,,,,,lOXNWNXKKKKKKKKKkc,,,,,,o0XWXo;,,,,,:kKXWNXKKKKKKKKKOl;,,,,,ckd;,,,,,,,,,,;cok0KKNKo;,,,,,;okkkkkkkkkkkkkkkkkkkkOKXNWMMMMMMMMMMMMMMMMMMMMMMM"
echo_c "MMMMMW0c,,,,,,;:cccccccccccccc:;,,,,,;o0XWXd;,,,,,,;;:::::::::::::;;,,,,,:x0XWXd;,,,,,,;:ccccccccccccc:;,,,,,;oOXWNk:,,,,,,,;;;;;;;;;;;;;;;;;;;;;o0XWMMW0l,,,,,,lOXWMW0occcccccc:;,,,,,:x0XMXo;,,,,,:kXNWXdccccccccc:;,,,,,;dOxlcc:::::cloxO0KKXWMXo;,,,,,,,;;;;;;;;;;;;;;;;;;;;:kKNMMMMMMMMMMMMMMMMMMMMMMMM"
echo_c "MMMMMW0c,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;o0XWWXd:;,,,,,,,,,,,,,,,,,,,,,,,;:lx0XWMXd;,,,,,,,,,,,,,,,,,,,,,,,,,;:lx0KNMNk:,,,,,,,;;;;;;;;;;;;;;;;;;;;;o0XWMMW0l,,,,,,lOXWMMWKo;,,,,,,,,,,;cok0XWMXo;,,,,,:kXNWKo;,,,,,,,,,,,,;:lx0K00OOxdddxO00KKXXWMMMXo;,,,,,,;;;::::::::::::::::::ckKNMMMMMMMMMMMMMMMMMMMMMMMM"
echo_c "MMMMMW0c,,,,,,:oddxddxxxddddxdl;,,,,,;o0XWMMWKOxxddddxo:,,,,,,:oxdddxxxO0XNWMMXd;,,,,,;ldddddddddddddddddxxOKXXWMMNk:,,,,,,lkOOOOOOOOOOOOOOOOOOOO0KXMMMW0l,,,,,,lOXWMMMMNkc;,,,,,,:ok0KXNWMMXd;,,,,,:kXNWXOddddddddddddxxOKXXNNXXKd:;:lOK0XNWMMMMMXo;,,,,,:x0O0000000000000000000KXNMMMMMMMMMMMMMMMMMMMMMMMM"
echo_c "MMMMMW0c,,,,,,l0XNNNNNNNNNNNWNk:,,,,,;o0XMMMMMWWNNNNNN0l,,,,,,lOXNNNNNNNWWMMMMXd;,,,,,:kKXNNNNNNNNNNNNNNNNNNWMMMMMWk:,,,,,,cxkOOOOOOOOOOOOOOOOOOOOOKNWMW0l,,,,,,lOXWMMMMMWKd:,,,,,;lOXWWMMMMXd;,,,,,:kXNMWNNNNNNNNNNNNNNNXXK0Okk00d;,,cOOxxkO0XWMMXo;,,,,,;okkkkkkkkkkkkkkkkkkkkkk0XNWMMMMMMMMMMMMMMMMMMMMMM"
echo_c "MMMMMW0c,,,,,,lOXWMMMMMMMMMMMWO:,,,,,;o0XWMMMMMMMMMMMW0l,,,,,,lOXWMMMMMMMMMMMMXd;,,,,,:xKNMMMMMMMMMMMMMMMMMMMMMMMMW0l,,,,,,,;;;;;;;;;;;;;;;;;;;;;;:xKNMW0l,,,,,,lOXWMMMMMMMNOc;,,,,,:dKNWMMMXd;,,,,,:kXNMMMMMMMMMMMMMMWNK0kxolccd0d;,,cOkc:clodkKNXx:,,,,,,,;;;;;;;;;;;;;;;;;;;;;;lOXWMMMMMMMMMMMMMMMMMMMMMM"
echo_c "MMMMMW0c;,,,,,o0XWMMMMMMMMMMMWOc,;,,,;o0XWMMMMMMMMMMMW0l;,,,,,lOXWMMMMMMMMMMMMXd;,,;,,:kKNMMMMMMMMMMMMMMMMMMMMMMMMMW0d:;;,,,,,,;,,,,,,,,,,,,,,,,,,;xKNMW0l;;,,,,lOXWMMMMMMMMWKd:;,;;,;lOXWMMXd;,;,,,ckKNMMMMMMMMMMMMMWX0kdc;,,,;d0d;,,cOk:,,,;:ldOKKkl:;;;;;;;;;;;;;;;;;;;;;;;;;;;lOXWMMMMMMMMMMMMMMMMMMMMMM"
echo_c "MMMMMWXOxxkxxkO0XWMMMMMMMMMMMWKkxxxxxkO0XMMMMMMMMMMMMWXOxxxxxxO0XWMMMMMMMMMMMMN0kxxxxxk0KNMMMMMMMMMMMMMMMMMMMMMMMMMMMNKOkkxxxkkxxxxxxxxxxxxxxxxxxxk0KNMWXOkxxxxxO0XWMMMMMMMMMMN0kxxxxxkOKXNMN0kxkkkxk0KNMMMMMMMMMMMMWXOxl;,,,,,;d0d;,,l0k:,,,,,;cdOKXXKOkkkkkkkkkkkkkkkkkkkkkkkkkkO0XWMMMMMMMMMMMMMMMMMMMMMM"
echo_c "MMMMMMWWWWWWWWNNWMMMMMMMMMMMMMWWWWWWWWNNWMMMMMMMMMMMMMWWWWWWWWWNWMMMMMMMMMMMMMWWNWWWWWNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWNWNWWMMWWWWWWWWWNWMMMMMMMMMMMMWWWWWNWWWWNWMWWWWWWWWNNWWMMMMMMMMMMMMW0ko;,,,,,,,ckOxodOOo;,,,,,,;ok0XWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMM"
echo_c "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOdo:,,,,,,,,:ldddoc;,,,,,,,:dk0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo_c "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOllo:;,,,,,,,,,,,,,,,,,,,;lddx0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo_c "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNkc:llc:;;,,,,,,,,,,,;:clddloOKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo_c "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0o::clllllcccccclllooolllx0KNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo_c "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0xoc:::ccccllccccccodk0XNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo_c "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNX0OkxdddddddxkO0XXNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo_c "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo_c "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo_c "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
echo
echo
echo
echo
echo
echo_c "Hello Guys Its Mike Manley"
echo
echo_c "Test"
echo
echo
echo_c "Test"











sleep 5
